# Generated by Django 3.0.5 on 2020-04-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='albums',
            field=models.ManyToManyField(null=True, to='api.Album'),
        ),
    ]
