# Generated by Django 3.0.5 on 2020-05-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200428_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
