# Generated by Django 3.0.5 on 2020-05-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_album_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
