# Generated by Django 3.0.5 on 2020-05-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_picture_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_description',
        ),
    ]
